spring:
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: production
  application:
    name: GiftShop
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    continue-on-error: false
    schema: classpath:sql/Schema.sql
    driver-class-name: org.h2.Driver
    initialization-mode: always

  h2:

     console:
       enabled: true
       path: /h2

server:
  port: ${PORT:9990}

  servlet:
    context-path: /
